"""initial schema

Revision ID: c46b2a362a35
Revises:
Create Date: 2026-09-29 04:37:34.716365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c46b2a362a35'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_scales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('max_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('competency_min_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('competency_min_points > 0 AND competency_min_points <= max_points', name=op.f('ck_grading_scales_competency_min_within_scale')),
    sa.CheckConstraint('max_points > 0', name=op.f('ck_grading_scales_max_points_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grading_scales')),
    sa.UniqueConstraint('name', name=op.f('uq_grading_scales_name'))
    )
    op.create_index(op.f('ix_grading_scales_public_id'), 'grading_scales', ['public_id'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_index(op.f('ix_subjects_public_id'), 'subjects', ['public_id'], unique=True)
    op.create_table('grades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('grade_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grading_scale_id', sa.Uuid(), nullable=False),
    sa.Column('max_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("label <> ''", name=op.f('ck_grades_grade_label_not_blank')),
    sa.CheckConstraint('grade_points <= max_points', name=op.f('ck_grades_grade_points_within_max')),
    sa.CheckConstraint('grade_points > 0', name=op.f('ck_grades_grade_points_positive')),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['grading_scales.id'], name=op.f('fk_grades_grading_scale_id_grading_scales'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('grading_scale_id', 'label', name='grade_label_per_scale')
    )
    op.create_index(op.f('ix_grades_grading_scale_id'), 'grades', ['grading_scale_id'], unique=False)
    op.create_index(op.f('ix_grades_public_id'), 'grades', ['public_id'], unique=True)
    op.create_table('universities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('grading_scale_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grading_scale_id'], ['grading_scales.id'], name=op.f('fk_universities_grading_scale_id_grading_scales'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities')),
    sa.UniqueConstraint('name', name=op.f('uq_universities_name'))
    )
    op.create_index(op.f('ix_universities_grading_scale_id'), 'universities', ['grading_scale_id'], unique=False)
    op.create_index(op.f('ix_universities_public_id'), 'universities', ['public_id'], unique=True)
    op.create_table('course_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_course_units_grade_id_grades'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_course_units_subject_id_subjects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_course_units_university_id_universities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_units')),
    sa.UniqueConstraint('university_id', 'code', name='course_unit_code_per_university')
    )
    op.create_index(op.f('ix_course_units_code'), 'course_units', ['code'], unique=False)
    op.create_index(op.f('ix_course_units_grade_id'), 'course_units', ['grade_id'], unique=False)
    op.create_index(op.f('ix_course_units_public_id'), 'course_units', ['public_id'], unique=True)
    op.create_index(op.f('ix_course_units_subject_id'), 'course_units', ['subject_id'], unique=False)
    op.create_index(op.f('ix_course_units_university_id'), 'course_units', ['university_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('academic_data_consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_users_university_id_universities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_university_id'), 'users', ['university_id'], unique=False)
    op.create_table('competencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_unit_id', sa.Uuid(), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='competency_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.Enum('transcript', 'portfolio', 'manual', name='verification_source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verified_at IS NULL OR status = 'verified'", name=op.f('ck_competencies_verified_requires_status')),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], name=op.f('fk_competencies_course_unit_id_course_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_competencies_grade_id_grades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_competencies_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_competencies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competencies')),
    sa.UniqueConstraint('user_id', 'course_unit_id', name='competency_user_unit')
    )
    op.create_index(op.f('ix_competencies_course_unit_id'), 'competencies', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_competencies_grade_id'), 'competencies', ['grade_id'], unique=False)
    op.create_index(op.f('ix_competencies_public_id'), 'competencies', ['public_id'], unique=True)
    op.create_index(op.f('ix_competencies_user_id'), 'competencies', ['user_id'], unique=False)
    op.create_table('help_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('tutee_id', sa.Uuid(), nullable=False),
    sa.Column('course_unit_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'matched', 'withdrawn', 'expired', name='help_request_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('matched_tutor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], name=op.f('fk_help_requests_course_unit_id_course_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['matched_tutor_id'], ['users.id'], name=op.f('fk_help_requests_matched_tutor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutee_id'], ['users.id'], name=op.f('fk_help_requests_tutee_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_requests'))
    )
    op.create_index(op.f('ix_help_requests_course_unit_id'), 'help_requests', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_help_requests_public_id'), 'help_requests', ['public_id'], unique=True)
    op.create_index(op.f('ix_help_requests_status'), 'help_requests', ['status'], unique=False)
    op.create_index(op.f('ix_help_requests_tutee_id'), 'help_requests', ['tutee_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('user_id', 'token_hash', name='refresh_token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_public_id'), 'refresh_tokens', ['public_id'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tutor_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('standing', sa.Enum('probationary', 'verified', 'reduced', 'suspended', name='tutor_standing', native_enum=False, create_constraint=True, length=32), server_default='probationary', nullable=False),
    sa.Column('completed_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('certified_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('suspended_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completed_sessions >= 0', name=op.f('ck_tutor_profiles_completed_sessions_non_negative')),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_tutor_profiles_rating_count_non_negative')),
    sa.CheckConstraint('rating_total >= 0', name=op.f('ck_tutor_profiles_rating_total_non_negative')),
    sa.CheckConstraint('rating_total >= rating_count', name=op.f('ck_tutor_profiles_rating_total_at_least_count')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tutor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_profiles'))
    )
    op.create_index(op.f('ix_tutor_profiles_public_id'), 'tutor_profiles', ['public_id'], unique=True)
    op.create_index(op.f('ix_tutor_profiles_user_id'), 'tutor_profiles', ['user_id'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('student', 'tutor', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role', name=op.f('pk_user_roles'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('help_request_id', sa.Uuid(), nullable=True),
    sa.Column('tutee_id', sa.Uuid(), nullable=False),
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('course_unit_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show', name='session_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cancelled_by_id', sa.Uuid(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status <> 'completed' OR (started_at IS NOT NULL AND ended_at IS NOT NULL)", name=op.f('ck_sessions_completed_session_has_times')),
    sa.CheckConstraint('duration_minutes >= 0', name=op.f('ck_sessions_duration_non_negative')),
    sa.CheckConstraint('tutee_id <> tutor_id', name=op.f('ck_sessions_session_parties_differ')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_sessions_cancelled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], name=op.f('fk_sessions_course_unit_id_course_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], name=op.f('fk_sessions_help_request_id_help_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutee_id'], ['users.id'], name=op.f('fk_sessions_tutee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['users.id'], name=op.f('fk_sessions_tutor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('help_request_id', name='session_per_request')
    )
    op.create_index(op.f('ix_sessions_course_unit_id'), 'sessions', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_sessions_public_id'), 'sessions', ['public_id'], unique=True)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_tutee_id'), 'sessions', ['tutee_id'], unique=False)
    op.create_index(op.f('ix_sessions_tutor_id'), 'sessions', ['tutor_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('rater_id', sa.Uuid(), nullable=False),
    sa.Column('ratee_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name=op.f('ck_ratings_score_within_scale')),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], name=op.f('fk_ratings_ratee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('fk_ratings_rater_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ratings_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('session_id', 'rater_id', name='rating_per_rater')
    )
    op.create_index(op.f('ix_ratings_public_id'), 'ratings', ['public_id'], unique=True)
    op.create_index(op.f('ix_ratings_ratee_id'), 'ratings', ['ratee_id'], unique=False)
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.create_index(op.f('ix_ratings_session_id'), 'ratings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_session_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_ratee_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_public_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_sessions_tutor_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tutee_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_public_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_course_unit_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tutor_profiles_user_id'), table_name='tutor_profiles')
    op.drop_index(op.f('ix_tutor_profiles_public_id'), table_name='tutor_profiles')
    op.drop_table('tutor_profiles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_public_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_help_requests_tutee_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_status'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_public_id'), table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_course_unit_id'), table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index(op.f('ix_competencies_user_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_public_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_grade_id'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_course_unit_id'), table_name='competencies')
    op.drop_table('competencies')
    op.drop_index(op.f('ix_users_university_id'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_course_units_university_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_subject_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_public_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_grade_id'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_code'), table_name='course_units')
    op.drop_table('course_units')
    op.drop_index(op.f('ix_universities_public_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_grading_scale_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_grades_public_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_grading_scale_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_subjects_public_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_grading_scales_public_id'), table_name='grading_scales')
    op.drop_table('grading_scales')
    # ### end Alembic commands ###
