name: peerpass_admin
description: "PeerPass MUST pilot administration console."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
